version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install yarn
  pre_build:
    commands:
      - echo Installing dependencies...
      - yarn
  build:
    commands:
      - echo Testing...
      - yarn run test
      - echo Building...
      - yarn run build
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: 'build'
