export const sampleData = [
  {
    name: 'Unity Butler',
    position: 'Marketing Designer',
    office: 'San Francisco',
    extn: '5384',
    startDate: '2009/12/09',
    salary: '$85,675',
  },
  {
    name: 'Tiger Nixon',
    position: 'System Architect',
    office: 'Edinburgh',
    extn: '5421',
    startDate: '2011/04/25',
    salary: '$320,800',
  },
  {
    name: 'Garrett Winters',
    position: 'Accountant',
    office: 'Tokyo',
    extn: '8422',
    startDate: '2011/07/25',
    salary: '$170,750',
  },
  {
    name: 'Ashton Cox',
    position: 'Junior Technical Author',
    office: 'San Francisco',
    extn: '1562',
    startDate: '2009/01/12',
    salary: '$86,000',
  },
  {
    name: 'Cedric Kelly',
    position: 'Senior Javascript Developer',
    office: 'Edinburgh',
    extn: '6224',
    startDate: '2012/03/29',
    salary: '$433,060',
  },
  {
    name: 'Brielle Williamson',
    position: 'Integration Specialist',
    office: 'New York',
    extn: '4804',
    startDate: '2012/12/02',
    salary: '$372,000',
  },
  {
    name: 'Herrod Chandler',
    position: 'Sales Assistant',
    office: 'San Francisco',
    extn: '9608',
    startDate: '2012/08/06',
    salary: '$137,500',
  },
  {
    name: 'Rhona Davidson',
    position: 'Integration Specialist',
    office: 'Tokyo',
    extn: '6200',
    startDate: '2010/10/14',
    salary: '$327,900',
  },
  {
    name: 'Colleen Hurst',
    position: 'Javascript Developer',
    office: 'San Francisco',
    extn: '2360',
    startDate: '2009/09/15',
    salary: '$205,500',
  },
  {
    name: 'Sonya Frost',
    position: 'Software Engineer',
    office: 'Edinburgh',
    extn: '1667',
    startDate: '2008/12/13',
    salary: '$103,600',
  },
  {
    name: 'Haley Kennedy',
    position: 'Senior Marketing Designer',
    office: 'London',
    extn: '3597',
    startDate: '2012/12/18',
    salary: '$313,500',
  },
  {
    name: 'Unity Butler',
    position: 'Marketing Designer',
    office: 'San Francisco',
    extn: '5384',
    startDate: '2009/12/09',
    salary: '$85,675',
  },
  {
    name: 'Tiger Nixon',
    position: 'System Architect',
    office: 'Edinburgh',
    extn: '5421',
    startDate: '2011/04/25',
    salary: '$320,800',
  },
  {
    name: 'Garrett Winters',
    position: 'Accountant',
    office: 'Tokyo',
    extn: '8422',
    startDate: '2011/07/25',
    salary: '$170,750',
  },
  {
    name: 'Ashton Cox',
    position: 'Junior Technical Author',
    office: 'San Francisco',
    extn: '1562',
    startDate: '2009/01/12',
    salary: '$86,000',
  },
  {
    name: 'Cedric Kelly',
    position: 'Senior Javascript Developer',
    office: 'Edinburgh',
    extn: '6224',
    startDate: '2012/03/29',
    salary: '$433,060',
  },
  {
    name: 'Brielle Williamson',
    position: 'Integration Specialist',
    office: 'New York',
    extn: '4804',
    startDate: '2012/12/02',
    salary: '$372,000',
  },
  {
    name: 'Herrod Chandler',
    position: 'Sales Assistant',
    office: 'San Francisco',
    extn: '9608',
    startDate: '2012/08/06',
    salary: '$137,500',
  },
  {
    name: 'Rhona Davidson',
    position: 'Integration Specialist',
    office: 'Tokyo',
    extn: '6200',
    startDate: '2010/10/14',
    salary: '$327,900',
  },
  {
    name: 'Colleen Hurst',
    position: 'Javascript Developer',
    office: 'San Francisco',
    extn: '2360',
    startDate: '2009/09/15',
    salary: '$205,500',
  },
  {
    name: 'Sonya Frost',
    position: 'Software Engineer',
    office: 'Edinburgh',
    extn: '1667',
    startDate: '2008/12/13',
    salary: '$103,600',
  },
  {
    name: 'Haley Kennedy',
    position: 'Senior Marketing Designer',
    office: 'London',
    extn: '3597',
    startDate: '2012/12/18',
    salary: '$313,500',
  },
  {
    name: 'Unity Butler',
    position: 'Marketing Designer',
    office: 'San Francisco',
    extn: '5384',
    startDate: '2009/12/09',
    salary: '$85,675',
  },
  {
    name: 'Tiger Nixon',
    position: 'System Architect',
    office: 'Edinburgh',
    extn: '5421',
    startDate: '2011/04/25',
    salary: '$320,800',
  },
  {
    name: 'Garrett Winters',
    position: 'Accountant',
    office: 'Tokyo',
    extn: '8422',
    startDate: '2011/07/25',
    salary: '$170,750',
  },
  {
    name: 'Ashton Cox',
    position: 'Junior Technical Author',
    office: 'San Francisco',
    extn: '1562',
    startDate: '2009/01/12',
    salary: '$86,000',
  },
  {
    name: 'Cedric Kelly',
    position: 'Senior Javascript Developer',
    office: 'Edinburgh',
    extn: '6224',
    startDate: '2012/03/29',
    salary: '$433,060',
  },
  {
    name: 'Brielle Williamson',
    position: 'Integration Specialist',
    office: 'New York',
    extn: '4804',
    startDate: '2012/12/02',
    salary: '$372,000',
  },
  {
    name: 'Herrod Chandler',
    position: 'Sales Assistant',
    office: 'San Francisco',
    extn: '9608',
    startDate: '2012/08/06',
    salary: '$137,500',
  },
  {
    name: 'Rhona Davidson',
    position: 'Integration Specialist',
    office: 'Tokyo',
    extn: '6200',
    startDate: '2010/10/14',
    salary: '$327,900',
  },
  {
    name: 'Colleen Hurst',
    position: 'Javascript Developer',
    office: 'San Francisco',
    extn: '2360',
    startDate: '2009/09/15',
    salary: '$205,500',
  },
  {
    name: 'Sonya Frost',
    position: 'Software Engineer',
    office: 'Edinburgh',
    extn: '1667',
    startDate: '2008/12/13',
    salary: '$103,600',
  },
  {
    name: 'Haley Kennedy',
    position: 'Senior Marketing Designer',
    office: 'London',
    extn: '3597',
    startDate: '2012/12/18',
    salary: '$313,500',
  },
];

export const columns = [
  { Header: 'Name', accessor: 'name' },
  { Header: 'Position', accessor: 'position' },
  { Header: 'Office', accessor: 'office' },
  { Header: 'Extn.', accessor: 'extn' },
  { Header: 'Start date', accessor: 'startDate' },
  { Header: 'Salary', accessor: 'salary' },
];
